import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lucide_icons/lucide_icons.dart';
import 'package:reboot_app_3/core/helpers/date_display_formater.dart';
import 'package:reboot_app_3/core/localization/localization.dart';
import 'package:reboot_app_3/core/shared_widgets/container.dart';
import 'package:reboot_app_3/core/theming/app-themes.dart';
import 'package:reboot_app_3/core/theming/spacing.dart';
import 'package:reboot_app_3/core/theming/text_styles.dart';
import 'package:reboot_app_3/features/home/data/calendar_notifier.dart';
import 'package:reboot_app_3/features/home/data/models/emotion.dart';
import 'package:reboot_app_3/features/home/data/models/emotion_model.dart';
import 'package:reboot_app_3/features/home/data/models/follow_up_option.dart';
import 'package:reboot_app_3/features/home/data/statistics_notifier.dart';
import 'package:reboot_app_3/features/home/data/streak_notifier.dart';
import 'package:reboot_app_3/features/shared/models/follow_up.dart';
import 'package:time_picker_spinner_pop_up/time_picker_spinner_pop_up.dart';
import 'package:reboot_app_3/features/home/data/follow_up_notifier.dart';
import 'package:reboot_app_3/features/home/data/emotion_notifier.dart';

class FollowUpSheet extends ConsumerStatefulWidget {
  FollowUpSheet(this.date, {super.key});

  DateTime date;
  @override
  _FollowUpSheetState createState() => _FollowUpSheetState();
}

class _FollowUpSheetState extends ConsumerState<FollowUpSheet> {
  Set<FollowUpOption> selectedFollowUps = {};
  Set<Emotion> selectedEmotions = {};
  bool addAllFollowUps = false; // New state for checkbox
  bool _isProcessing = false;
  bool _showEmotions = false; // New state for showing emotions section

  final List<FollowUpOption> followUpOptions = [
    FollowUpOption(icon: LucideIcons.trophy, translationKey: 'free-day'),
    FollowUpOption(icon: LucideIcons.planeLanding, translationKey: 'slipUp'),
    FollowUpOption(icon: LucideIcons.heartCrack, translationKey: 'relapse'),
    FollowUpOption(icon: LucideIcons.play, translationKey: 'pornOnly'),
    FollowUpOption(icon: LucideIcons.hand, translationKey: 'mastOnly'),
  ];

  void toggleFollowUp(FollowUpOption followUpOption) {
    setState(() {
      if (followUpOption.translationKey == 'free-day') {
        if (selectedFollowUps.contains(followUpOption)) {
          selectedFollowUps.remove(followUpOption);
        } else {
          selectedFollowUps.clear();
          selectedFollowUps.add(followUpOption);
          addAllFollowUps = false;
        }
      } else {
        selectedFollowUps
            .removeWhere((option) => option.translationKey == 'free-day');

        if (selectedFollowUps.contains(followUpOption)) {
          selectedFollowUps.remove(followUpOption);
          if (followUpOption.translationKey == 'relapse') {
            addAllFollowUps = false;
          }
        } else {
          selectedFollowUps.add(followUpOption);
          if (followUpOption.translationKey == 'relapse') {
            addAllFollowUps = true;
          }
        }
      }
    });
    HapticFeedback.selectionClick();
  }

  void toggleEmotion(Emotion emotion) {
    setState(() {
      if (selectedEmotions.contains(emotion)) {
        selectedEmotions.remove(emotion);
      } else {
        selectedEmotions.add(emotion);
      }
    });
    HapticFeedback.selectionClick(); // Haptic feedback on selection
  }

  Future<void> _saveFollowUpsAndEmotions() async {
    final followUpNotifier = ref.read(followUpNotifierProvider.notifier);
    final emotionNotifier = ref.read(emotionNotifierProvider.notifier);

    if (selectedFollowUps
        .any((option) => option.translationKey == 'free-day')) {
      await followUpNotifier.deleteFollowUpsByDate(widget.date);
      return;
    }

    final followUps = selectedFollowUps.expand((option) {
      if (option.translationKey == 'relapse' && addAllFollowUps) {
        return followUpOptions.map((opt) {
          return FollowUpModel(
            id: '', // ID will be generated by Firestore
            type: FollowUpType.values.firstWhere(
              (e) => e.name == opt.translationKey,
              orElse: () => FollowUpType.relapse,
            ),
            time: widget.date,
          );
        }).toList();
      } else {
        return [
          FollowUpModel(
            id: '', // ID will be generated by Firestore
            type: FollowUpType.values.firstWhere(
              (e) => e.name == option.translationKey,
              orElse: () => FollowUpType.relapse,
            ),
            time: widget.date,
          )
        ];
      }
    }).toList();

    final emotions = selectedEmotions.map((emotion) {
      return EmotionModel(
        id: '', // ID will be generated by Firestore
        emotionEmoji: emotion.emotionEmoji,
        emotionName: emotion.emotionNameTranslationKey,
        date: widget.date,
      );
    }).toList();

    await followUpNotifier.createMultipleFollowUps(followUps);
    await emotionNotifier.createMultipleEmotions(emotions);
  }

  @override
  Widget build(BuildContext context) {
    final locale = ref.watch(localeNotifierProvider);
    final theme = AppTheme.of(context);

    // Get free day option and other options separately
    final freeDayOption = followUpOptions
        .firstWhere((option) => option.translationKey == 'free-day');
    final otherOptions = followUpOptions
        .where((option) => option.translationKey != 'free-day')
        .toList();

    return IntrinsicHeight(
      child: Container(
        color: theme.backgroundColor,
        // padding: EdgeInsets.all(16),
        width: MediaQuery.of(context).size.width,
        child: Column(
          children: [
            // Fixed top row with date picker
            Padding(
              padding: const EdgeInsets.all(16),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  TimePickerSpinnerPopUp(
                    maxTime: DateTime.now(),
                    mode: CupertinoDatePickerMode.dateAndTime,
                    barrierColor: theme.primary[50]!,
                    padding: const EdgeInsets.fromLTRB(12, 10, 12, 10),
                    locale: locale,
                    cancelTextStyle: TextStyles.caption.copyWith(
                      color: theme.primary[600],
                    ),
                    confirmTextStyle: TextStyles.caption.copyWith(
                      color: theme.primary[600],
                    ),
                    textStyle: TextStyles.caption.copyWith(
                      color: theme.primary[600],
                    ),
                    timeFormat: "d - MMMM - yyyy hh:mm a",
                    timeWidgetBuilder: (dateTime) {
                      return WidgetsContainer(
                        padding: EdgeInsets.all(8),
                        backgroundColor: theme.backgroundColor,
                        borderSide:
                            BorderSide(color: theme.grey[600]!, width: 0.5),
                        borderRadius: BorderRadius.circular(8),
                        boxShadow: [
                          BoxShadow(
                            color: Color.fromRGBO(60, 64, 67, 0.3),
                            blurRadius: 2,
                            spreadRadius: 0,
                            offset: Offset(
                              0,
                              1,
                            ),
                          ),
                          BoxShadow(
                            color: Color.fromRGBO(60, 64, 67, 0.15),
                            blurRadius: 6,
                            spreadRadius: 2,
                            offset: Offset(
                              0,
                              2,
                            ),
                          ),
                        ],
                        child: Text(
                          getDisplayDateTime(dateTime, locale!.languageCode),
                          style: TextStyles.body,
                        ),
                      );
                    },
                    initTime: widget.date,
                    cancelText:
                        AppLocalizations.of(context).translate("cancel"),
                    confirmText:
                        AppLocalizations.of(context).translate("confirm"),
                    onChange: (date) {
                      setState(() {
                        widget.date = date;
                      });
                    },
                  ),
                  GestureDetector(
                    onTap: () {
                      Navigator.pop(context);
                    },
                    child: Icon(
                      LucideIcons.xCircle,
                    ),
                  )
                ],
              ),
            ),

            // Scrollable middle content
            Expanded(
              child: SingleChildScrollView(
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        AppLocalizations.of(context)
                            .translate('what-you-want-to-add'),
                        style: TextStyles.h6,
                      ),
                      verticalSpace(Spacing.points8),
                      // Free day option at the top
                      FollowUpButton(
                        followUpOption: freeDayOption,
                        isSelected: selectedFollowUps.contains(freeDayOption),
                        onTap: () => toggleFollowUp(freeDayOption),
                      ),
                      verticalSpace(Spacing.points8),
                      // Other options in grid
                      Column(
                        children: [
                          for (int i = 0; i < otherOptions.length; i += 2)
                            Padding(
                              padding: const EdgeInsets.only(bottom: 8.0),
                              child: Row(
                                children: [
                                  Expanded(
                                    child: FollowUpButton(
                                      followUpOption: otherOptions[i],
                                      isSelected: selectedFollowUps
                                          .contains(otherOptions[i]),
                                      onTap: () =>
                                          toggleFollowUp(otherOptions[i]),
                                    ),
                                  ),
                                  if (i + 1 < otherOptions.length) ...[
                                    horizontalSpace(Spacing.points8),
                                    Expanded(
                                      child: FollowUpButton(
                                        followUpOption: otherOptions[i + 1],
                                        isSelected: selectedFollowUps
                                            .contains(otherOptions[i + 1]),
                                        onTap: () =>
                                            toggleFollowUp(otherOptions[i + 1]),
                                      ),
                                    ),
                                  ],
                                ],
                              ),
                            ),
                        ],
                      ),
                      verticalSpace(Spacing.points8),

                      // Warning message moved here, after the options
                      if (selectedFollowUps
                          .any((option) => option.translationKey == 'free-day'))
                        WidgetsContainer(
                          padding: const EdgeInsets.all(12),
                          backgroundColor: theme.success[50],
                          borderRadius: BorderRadius.circular(8),
                          borderSide: BorderSide(
                            color: theme.success[300]!,
                            width: 0.75,
                          ),
                          child: Row(
                            children: [
                              Icon(
                                LucideIcons.star,
                                color: theme.success[700],
                              ),
                              horizontalSpace(Spacing.points8),
                              Expanded(
                                child: Text(
                                  AppLocalizations.of(context)
                                      .translate('free-day-warning-message'),
                                  style: TextStyles.small
                                      .copyWith(color: theme.success[700]),
                                ),
                              ),
                            ],
                          ),
                        ),

                      if (selectedFollowUps
                          .any((option) => option.translationKey == 'relapse'))
                        Column(
                          children: [
                            verticalSpace(Spacing.points8),
                            Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Checkbox(
                                  value: addAllFollowUps,
                                  onChanged: (value) {
                                    setState(() {
                                      addAllFollowUps = value!;
                                    });
                                  },
                                ),
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [
                                      Text(
                                        AppLocalizations.of(context)
                                            .translate('add-all-follow-ups'),
                                        style: TextStyles.smallBold,
                                      ),
                                      Text(
                                        AppLocalizations.of(context).translate(
                                            'add-all-follow-ups-desc'),
                                        style: TextStyles.small.copyWith(
                                          color: theme.grey[500],
                                        ),
                                        softWrap: true,
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                      verticalSpace(Spacing.points4),
                      GestureDetector(
                        onTap: () {
                          setState(() {
                            _showEmotions = !_showEmotions;
                          });
                          HapticFeedback.selectionClick();
                        },
                        child: WidgetsContainer(
                          padding: EdgeInsets.all(12),
                          backgroundColor: theme.primary[50],
                          borderSide: BorderSide(
                            color: theme.primary[200]!,
                            width: 0.75,
                          ),
                          borderRadius: BorderRadius.circular(12),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text(
                                AppLocalizations.of(context)
                                    .translate('how-do-you-feel'),
                                style: TextStyles.caption,
                              ),
                              Icon(
                                _showEmotions
                                    ? LucideIcons.chevronUp
                                    : LucideIcons.chevronDown,
                                color: theme.grey[600],
                              ),
                            ],
                          ),
                        ),
                      ),
                      if (_showEmotions) ...[
                        verticalSpace(Spacing.points8),
                        Text(
                          AppLocalizations.of(context)
                              .translate('negative-feelings'),
                          style: TextStyles.footnoteSelected.copyWith(
                            color: theme.grey[700],
                          ),
                        ),
                        verticalSpace(Spacing.points4),
                        Wrap(
                          spacing: 8,
                          runSpacing: 8,
                          children: badEmotions.map((emotion) {
                            return EmotionButton(
                              emotion: emotion,
                              isSelected: selectedEmotions.contains(emotion),
                              onTap: () => toggleEmotion(emotion),
                            );
                          }).toList(),
                        ),
                        verticalSpace(Spacing.points16),
                        Text(
                          AppLocalizations.of(context)
                              .translate('positive-feelings'),
                          style: TextStyles.footnoteSelected.copyWith(
                            color: theme.grey[700],
                          ),
                        ),
                        verticalSpace(Spacing.points4),
                        Wrap(
                          spacing: 8,
                          runSpacing: 8,
                          children: goodEmotions.map((emotion) {
                            return EmotionButton(
                              emotion: emotion,
                              isSelected: selectedEmotions.contains(emotion),
                              onTap: () => toggleEmotion(emotion),
                            );
                          }).toList(),
                        ),
                        verticalSpace(Spacing.points16),
                      ],
                    ],
                  ),
                ),
              ),
            ),
            // Fixed bottom row with save/cancel buttons
            Column(
              children: [
                Container(
                  color: theme.backgroundColor,
                  padding: EdgeInsets.all(16),
                  child: Row(
                    children: [
                      Expanded(
                        child: GestureDetector(
                          onTap: _isProcessing
                              ? null
                              : () async {
                                  setState(() => _isProcessing = true);

                                  try {
                                    await _saveFollowUpsAndEmotions();
                                    if (mounted) {
                                      await Future.wait([
                                        ref.refresh(
                                            statisticsNotifierProvider.future),
                                        ref.refresh(
                                            streakNotifierProvider.future),
                                        ref.refresh(
                                            followUpNotifierProvider.future),
                                        ref.refresh(
                                            calendarNotifierProvider.future),
                                      ]);

                                      Navigator.pop(context);
                                    }
                                  } catch (e) {
                                    if (mounted) {
                                      setState(() => _isProcessing = false);
                                    }
                                  }
                                },
                          child: WidgetsContainer(
                            borderRadius: BorderRadius.circular(10),
                            backgroundColor: _isProcessing
                                ? theme.grey[400]
                                : theme.primary[600],
                            child: Center(
                              child: Row(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  if (_isProcessing) ...[
                                    SizedBox(
                                      height: 20,
                                      width: 20,
                                      child: CircularProgressIndicator(
                                        strokeWidth: 2,
                                        valueColor:
                                            AlwaysStoppedAnimation<Color>(
                                          theme.grey[50]!,
                                        ),
                                      ),
                                    ),
                                    horizontalSpace(Spacing.points8),
                                    Text(
                                      AppLocalizations.of(context)
                                          .translate('saving'),
                                      style: TextStyles.caption
                                          .copyWith(color: theme.grey[50]),
                                    ),
                                  ] else
                                    Text(
                                      AppLocalizations.of(context)
                                          .translate('save'),
                                      style: TextStyles.caption
                                          .copyWith(color: theme.grey[50]),
                                    ),
                                ],
                              ),
                            ),
                          ),
                        ),
                      ),
                      horizontalSpace(Spacing.points8),
                      Expanded(
                        child: GestureDetector(
                          onTap: () {
                            HapticFeedback.lightImpact();
                            Navigator.pop(context);
                          },
                          child: WidgetsContainer(
                            borderRadius: BorderRadius.circular(10),
                            backgroundColor: theme.backgroundColor,
                            borderSide: BorderSide(
                                color: theme.grey[600]!, width: 0.25),
                            child: Center(
                              child: Text(
                                AppLocalizations.of(context)
                                    .translate('cancel'),
                                style: TextStyles.caption
                                    .copyWith(color: theme.grey[900]),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class FollowUpButton extends StatelessWidget {
  const FollowUpButton({
    required this.followUpOption,
    required this.isSelected,
    required this.onTap,
    super.key,
  });

  final FollowUpOption followUpOption;
  final bool isSelected;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final theme = AppTheme.of(context);

    return GestureDetector(
      onTap: () {
        HapticFeedback.selectionClick();
        onTap();
      },
      child: WidgetsContainer(
        padding: EdgeInsets.all(12),
        backgroundColor: theme.backgroundColor,
        borderSide: BorderSide(
          color: isSelected ? theme.success[600]! : theme.grey[600]!,
          width: isSelected ? 1 : 0.5,
        ),
        child: Row(
          children: [
            Icon(
              followUpOption.icon,
              color: theme.primary[600],
              size: 20,
            ),
            horizontalSpace(Spacing.points8),
            Text(
              AppLocalizations.of(context)
                  .translate(followUpOption.translationKey),
              style: TextStyles.small,
            ),
          ],
        ),
      ),
    );
  }
}

class EmotionButton extends StatelessWidget {
  const EmotionButton({
    required this.emotion,
    required this.isSelected,
    required this.onTap,
    super.key,
  });

  final Emotion emotion;
  final bool isSelected;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final theme = AppTheme.of(context);

    return IntrinsicWidth(
      child: GestureDetector(
        onTap: () {
          HapticFeedback.selectionClick();
          onTap();
        },
        child: WidgetsContainer(
          padding: EdgeInsets.all(4),
          backgroundColor: theme.backgroundColor,
          borderSide: BorderSide(
            color: isSelected ? theme.success[600]! : theme.grey[600]!,
            width: isSelected ? 0.75 : 0.25,
          ),
          borderRadius: BorderRadius.circular(8),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Text(
                emotion.emotionEmoji,
                style: TextStyles.bodyLarge.copyWith(height: 1.2),
              ),
              horizontalSpace(Spacing.points4),
              Text(
                AppLocalizations.of(context)
                    .translate(emotion.emotionNameTranslationKey),
                style: TextStyles.small,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
