---
workflows:
  android-workflow-id:
    name:
      Android Workflow
      # .......
      # .......
      # .......
  ios-workflow-id:
    name: iOS Workflow
    environment:
      flutter: fvm
      flavor: stable
