workflows:
  android-internal-test-workflow:
    max_build_duration: 120
    name: Android Workflow
    environment:
      android_signing:
        - android-signing-key
      flutter: stable
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.amjadkhalfan.reboot_app_3"
        GOOGLE_PLAY_TRACK: alpha
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build AAB file
        script: |
          VERSION=$(cat pubspec.yaml | grep 'version:' | head -1 | awk '{print $2}' | cut -d '+' -f 1)
          LATEST_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK")
          BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          if [ $BUILD_NUMBER -lt 10 ]; then
            BUILD_NUMBER="0$BUILD_NUMBER"
          fi
          flutter build appbundle --release \
            --build-name=$VERSION \
            --build-number=$BUILD_NUMBER \
            -PVERSION_CODE=$BUILD_NUMBER \
            -PVERSION_NAME="$BUILD_NUMBER ($VERSION)"
          echo "Generated AAB files:"
          find build -name "*.aab"
          echo "Generated mapping files:"
          find build -name "mapping.txt"

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: closed
        submit_as_draft: true

  ios-testflight-workflow:
    name: iOS Workflow
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.amjadkhalfan.RebootApp
      vars:
        APP_STORE_APPLE_ID: 1531562469
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ios
        script: |
          VERSION=$(cat pubspec.yaml | grep 'version:' | head -1 | awk '{print $2}' | cut -d '+' -f 1)
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1))
          flutter build ios --release \
            --build-name=$VERSION \
            --build-number=$BUILD_NUMBER
          echo "Generated Xcode project files:"
          find build/ios -name "*.xcodeproj"
      - name: Create IPA file
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/ios/archive/Runner.xcarchive archive

          xcodebuild -exportArchive \
          -archivePath $PWD/build/ios/archive/Runner.xcarchive \
          -exportOptionsPlist ios/Runner/Info.plist \
          -exportPath $PWD/build/ios/ipa

          echo "Generated IPA files:"
          find build/ios/ipa -name "*.ipa"
          echo "Generated Xcode build logs:"
          find /tmp/xcodebuild_logs -name "*.log"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    integrations:
      app_store_connect: Codemagic
    publishing:
      email:
        recipients:
          - admin@ta3afi.app
          - i4mjad@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
