---
workflows:
  android-internal-test-workflow:
    max_build_duration: 120
    name: Android Workflow
    environment:
      android_signing:
        - android-signing-key
      flutter: stable
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.amjadkhalfan.reboot_app_3"
        GOOGLE_PLAY_TRACK: alpha
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Fetch and Increment Build Number
        script: |
          LATEST_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK")
          if [ -z "$LATEST_BUILD_NUMBER" ]; then
            echo "Failed to fetch the latest build number."
            exit 1
          fi
          echo "Latest build number: $LATEST_BUILD_NUMBER"
          BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          if [ -z "$BUILD_NUMBER" ]; then
            echo "Failed to increment the build number."
            exit 1
          fi
          echo "New build number: $BUILD_NUMBER"
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$(BUILD_NUMBER + 1)
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: closed
        submit_as_draft: true

  ios-workflow-id:
    name: iOS Workflow
