workflows:
  android-internal-test-workflow:
    max_build_duration: 120
    name: Android Workflow
    environment:
      android_signing:
        - android-signing-key
      flutter: stable
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.amjadkhalfan.reboot_app_3"
        GOOGLE_PLAY_TRACK: alpha
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build AAB file
        script: |
          VERSION=$(cat pubspec.yaml | grep 'version:' | head -1 | awk '{print $2}' | cut -d '+' -f 1)
          LATEST_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK")
          BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          if [ $BUILD_NUMBER -lt 10 ]; then
            BUILD_NUMBER="0$BUILD_NUMBER"
          fi
          FORMATTED_BUILD_NAME="${BUILD_NUMBER} (${VERSION})"
          flutter build appbundle --release \
            --build-name=$FORMATTED_BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            -PVERSION_CODE=$BUILD_NUMBER \
            -PVERSION_NAME=$FORMATTED_BUILD_NAME

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: closed
        submit_as_draft: true

  ios-testflight-workflow:
    name: iOS Workflow
