workflows:
  android-internal-test-workflow:
    max_build_duration: 120
    name: Android Workflow
    environment:
      android_signing:
        - android-signing-key
      flutter: stable
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.amjadkhalfan.reboot_app_3"
        GOOGLE_PLAY_TRACK: alpha
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build AAB file
        script: |
          VERSION=$(cat pubspec.yaml | grep 'version:' | head -1 | awk '{print $2}' | cut -d '+' -f 1)
          LATEST_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK")
          BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          if [ $BUILD_NUMBER -lt 10 ]; then
            BUILD_NUMBER="0$BUILD_NUMBER"
          fi
          flutter build appbundle --release \
            --build-name=$VERSION \
            --build-number=$BUILD_NUMBER \
            -PVERSION_CODE=$BUILD_NUMBER \
            -PVERSION_NAME="$BUILD_NUMBER ($VERSION)"

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: closed
        submit_as_draft: true

  ios-testflight-workflow:
    name: iOS Workflow
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.amjadkhalfan.RebootApp
      vars:
        APP_STORE_APPLE_ID: 1531562469
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Update Info.plist
        script: |
          # Extract version and build number from codemagic.yaml
          VERSION=$(cat pubspec.yaml | grep 'version:' | head -1 | awk '{print $2}' | cut -d '+' -f 1)
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID") + 1))

          # Path to Info.plist
          PLIST_PATH="./ios/Runner/Info.plist"

          # Update CFBundleShortVersionString and CFBundleVersion in Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" "$PLIST_PATH"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$PLIST_PATH"

      - name: Flutter build ipa
        script: |
          VERSION=$(cat pubspec.yaml | grep 'version:' | head -1 | awk '{print $2}' | cut -d '+' -f 1)
          BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID")
          flutter build ipa --release --export-options-plist=ios/buildInfo.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    integrations:
      app_store_connect: Taa'afi Codemagic
    publishing:
      email:
        recipients:
          - i4mjad@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: false
