workflows:
  android-internal-test-workflow:
    max_build_duration: 120
    name: Android Workflow
    environment:
      android_signing:
        - android-signing-key
      flutter: stable
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "com.amjadkhalfan.reboot_app_3"
        GOOGLE_PLAY_TRACK: alpha
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Fetch version from pubspec.yaml
        script: |
          VERSION_NAME=$(grep 'version:' pubspec.yaml | sed 's/version: //g' | cut -d '+' -f1)
          echo "Fetched version name: $VERSION_NAME"
          VERSION_NUMBER=$(echo $VERSION_NAME | sed 's/\.//g')
          if [ ${#VERSION_NUMBER} -ne 3 ]; then
            echo "Version number format is incorrect. Expected format X.Y.Z"
            exit 1
          fi
      - name: Build AAB file
        script: |
          LATEST_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK")
          BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          BUILD_NUMBER_PADDED=$(printf "%02d" $((BUILD_NUMBER % 100)))
          VERSION_CODE="${VERSION_NUMBER}${BUILD_NUMBER_PADDED}"
          echo "Final version code: $VERSION_CODE"
          flutter build appbundle --release \
            --build-name="$VERSION_NAME ($VERSION_CODE)" \
            --build-number=$VERSION_CODE \
            -PVERSION_CODE=$VERSION_CODE \
            -PVERSION_NAME=$VERSION_NAME
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: closed
        submit_as_draft: true

  ios-testflight-workflow:
    name: iOS Test Workflow
