abstract class AnalyticsClient {
  Future<void> trackAppOpened();
  Future<void> trackOnboarding();
  Future<void> trackNewFollowUpAdded();
  Future<void> trackFollowUpUpdated();
  Future<void> trackFollowUpRemoved();
  Future<void> trackAppClosed();
  Future<void> trackOnboardingStart();
  Future<void> trackOnboardingFinish();
  Future<void> trackUserLogin();
  Future<void> trackUserLogout();
  Future<void> trackUserSignup();
  Future<void> trackUserUpdateProfile();
  Future<void> trackUserDeleteAccount();
  Future<void> trackScreenView(String routeName, String action);
  Future<void> identifyUser(String userId);
  Future<void> resetUser();
  Future<void> trackUserResetDataStarted();
  Future<void> trackUserResetDataFinished();
  Future<void> trackActivityFetchStarted();
  Future<void> trackActivityFetchFinished();
  Future<void> trackActivityFetchFailed();
  Future<void> trackActivitySubscriptionStarted();
  Future<void> trackActivitySubscriptionFinished();
  Future<void> trackActivitySubscriptionFailed();
  Future<void> trackProgressCalculationStarted();
  Future<void> trackProgressCalculationFinished();
  Future<void> trackProgressCalculationFailed();
  Future<void> trackTaskCompletionStarted();
  Future<void> trackTaskCompletionFinished();
  Future<void> trackTaskCompletionFailed();
  Future<void> trackActivityUpdateStarted();
  Future<void> trackActivityUpdateFinished();
  Future<void> trackActivityUpdateFailed();
  Future<void> trackActivityDeleteStarted();
  Future<void> trackActivityDeleteFinished();
  Future<void> trackActivityDeleteFailed();
}
