import SwiftUI

enum AppIcon: String, CaseIterable {
    case alertCircle = "exclamationmark.circle"
    case alertTriangle = "exclamationmark.triangle"
    case check = "checkmark"
    case checkCircle = "checkmark.circle.fill"
    case checkSquare = "checkmark.square"
    case chevronRight = "chevron.right"
    case chevronForward = "chevron.forward"
    case chevronDown = "chevron.down"
    case clock = "clock"
    case eye = "eye"
    case eyeOff = "eye.slash"
    case info = "info.circle"
    case mail = "envelope"
    case pencil = "pencil"
    case shieldOff = "shield.slash"
    case signOut = "rectangle.portrait.and.arrow.right"
    case trash = "trash"
    case userX = "person.crop.circle.badge.xmark"
    case warning = "exclamationmark.triangle.fill"
    case wifiOff = "wifi.slash"
    case xmark = "xmark"
    case xmarkCircle = "xmark.circle.fill"
    case gift = "gift"
    case sparkles = "sparkles"
    case paintbrush = "paintbrush"
    case sunMax = "sun.max"
    case moon = "moon"
    case globe = "globe"
    case person = "person"
    case personCircle = "person.circle"
    case star = "star"
    case paperplane = "paperplane.fill"
    case arrowCounterclockwise = "arrow.counterclockwise"
    case docText = "doc.text"
    case handRaised = "hand.raised"
    case heartSlash = "heart.slash"
    case chartBar = "chart.bar"
    case listBullet = "list.bullet"
    case calendarBadgeMinus = "calendar.badge.minus"
    case faceFrown = "face.frowning"
    case figureWalk = "figure.walk"
    case shieldExclamation = "shield.lefthalf.filled.trianglebadge.exclamationmark"
    case radioButton = "circle"
    case radioButtonFilled = "circle.inset.filled"
    case crownFill = "crown.fill"

    var systemName: String { rawValue }

    /// Brand plus icon from Asset Catalog (not SF Symbol)
    static let plusIconName = "Ta3aafiPlus"
}
