import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { type Locale, fallbackLng } from "./i18n/settings";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children; // Remove html and body tags from root layout
}

// import "./globals.css";
// import type { Metadata } from "next";
// import { type Locale, fallbackLng } from "./i18n/settings";

// export const metadata: Metadata = {
//   title: "Coming Soon",
//   description: "Our app is coming soon!",
// };

// export default function RootLayout({
//   children,
//   params,
// }: {
//   children: React.ReactNode;
//   params: { lang: Locale };
// }) {
//   const lang = params.lang || fallbackLng;
//   return (
//     <html lang={lang} dir={lang === "ar" ? "rtl" : "ltr"}>
//       <body>{children}</body>
//     </html>
//   );
// }
