// private navigators

enum RouteNames {
  home,
  account,
  vault,
  ta3afiPlus,
  contents,
  onboarding,
  login,
  signup,
  forgotPassword,
  completeAccountRegisteration,
  confirmUserDetails,
  confirmUserEmail,
  loading,
  dayOverview,
  diaries,
  diary,
  library,
  libraryList,
  contentType,
  activities,
  allTasks,
  addActivity,
  activityOverview,
  ongoingActivity,
  accountDelete,
  contentLists,
  vaultSettings,
  activitiesNotifications,
  community,
  groups, // New groups main route
  // Community routes
  communityOnboarding,
  forumHome,
  // Groups routes
  groupsOnboarding,
  postDetail,
  newPost,
  replyComposer,
  groupList,
  groupDetail,
  groupChat,
  groupChallenge,
  globalChallengeList,
  communityProfile,
  userReports,
  reportConversation,
  notifications,
  userProfile,
  banned,
  allPosts,
  categoryPosts,
}
