// private navigators

enum RouteNames {
  home,
  account,
  vault,
  ta3afiPlus,
  contents,
  onboarding,
  login,
  signup,
  forgotPassword,
  completeAccountRegisteration,
  confirmUserDetails,
  confirmUserEmail,
  loading,
  dayOverview,
  diaries,
  diary,
  library,
  libraryList,
  contentType,
  activities,
  allTasks,
  addActivity,
  activityOverview,
  ongoingActivity,
  accountDelete,
  contentLists,
  vaultSettings,
  activitiesNotifications,
  community,
  userReports,
  reportConversation,
}
