// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGLGAfOFa3cyz4AkS7B9QykU0D85TlKi8',
    appId: '1:364568176835:android:80340385239c13f5e31a76',
    messagingSenderId: '364568176835',
    projectId: 'rebootapp-37a30',
    databaseURL: 'https://rebootapp-37a30.firebaseio.com',
    storageBucket: 'rebootapp-37a30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzFrgUYgKUHSuWfPPF2YTwXdDwcy8KH3E',
    appId: '1:364568176835:ios:1ba9bda88b02b7e0e31a76',
    messagingSenderId: '364568176835',
    projectId: 'rebootapp-37a30',
    databaseURL: 'https://rebootapp-37a30.firebaseio.com',
    storageBucket: 'rebootapp-37a30.appspot.com',
    androidClientId: '364568176835-0ke3jcmnqfsmq2pf73dihe6369cekh67.apps.googleusercontent.com',
    iosClientId: '364568176835-j2eijl6oi1bs1bi1c755e0f3oj1h2eta.apps.googleusercontent.com',
    iosBundleId: 'com.amjadkhalfan.RebootApp',
  );
}
