import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "T",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body className="font-sans antialiased">{children}</body>
    </html>
  );
}
